version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 2
    max_jobs: 0
  middleware: ["gzip"]

logs:
  mode: development
  encoding: json
  channels:
    http:
      level: info
    server:
      level: info
