version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 4
    max_jobs: 500
  middleware: ["gzip"]

logs:
  mode: production
  encoding: json
