<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628165900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE events (global_position BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id UUID NOT NULL, stream_type VARCHAR(128) NOT NULL, stream_id VARCHAR(128) NOT NULL, version INT NOT NULL, event_type VARCHAR(255) NOT NULL, schema_version INT NOT NULL, payload JSONB NOT NULL, metadata JSONB NOT NULL, occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, recorded_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (global_position))');
        $this->addSql('CREATE UNIQUE INDEX uniq_events_stream_version ON events (stream_type, stream_id, version)');
        $this->addSql('CREATE UNIQUE INDEX uniq_events_event_id ON events (event_id)');
        $this->addSql('CREATE TABLE idempotency_keys (idempotency_key VARCHAR(255) NOT NULL, route VARCHAR(255) NOT NULL, request_hash VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL, response_status INT DEFAULT NULL, response_headers JSONB DEFAULT NULL, response_body TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (idempotency_key, route))');
        $this->addSql('CREATE INDEX idx_idempotency_expires_at ON idempotency_keys (expires_at)');
        $this->addSql('CREATE TABLE account_balances (account_id VARCHAR(128) NOT NULL, currency VARCHAR(3) NOT NULL, available BIGINT NOT NULL, reserved BIGINT NOT NULL, total BIGINT NOT NULL, version INT NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (account_id))');
        $this->addSql('CREATE TABLE account_statement (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id VARCHAR(128) NOT NULL, global_position BIGINT NOT NULL, entry_type VARCHAR(32) NOT NULL, amount BIGINT NOT NULL, currency VARCHAR(3) NOT NULL, occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_statement_global_position ON account_statement (global_position)');
        $this->addSql('CREATE INDEX idx_statement_account ON account_statement (account_id, global_position)');
        $this->addSql('CREATE TABLE projection_checkpoints (name VARCHAR(64) NOT NULL, position BIGINT NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (name))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE idempotency_keys');
        $this->addSql('DROP TABLE account_balances');
        $this->addSql('DROP TABLE account_statement');
        $this->addSql('DROP TABLE projection_checkpoints');
    }
}
