apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ledger-core.fullname" . }}-config
  labels:
    {{- include "ledger-core.labels" . | nindent 4 }}
data:
  {{- include "ledger-core.configData" . | nindent 2 }}
