apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger-core.fullname" . }}-secret
  labels:
    {{- include "ledger-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  API_KEY: {{ .Values.secret.apiKey | quote }}
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
