{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ledger-core.fullname" . }}
  labels:
    {{- include "ledger-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ledger-core.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
