apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger-core.fullname" . }}-api
  labels:
    {{- include "ledger-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ledger-core.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: 2112
      targetPort: metrics
