<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Types\Types;
use Doctrine\Migrations\Provider\SchemaProvider;

/**
 * The single source of truth for the database schema.
 *
 * Migrations are generated by diffing this schema against the database
 * (`doctrine:migrations:diff`) — never hand-authored. To change the schema, edit
 * this configurator and generate the resulting migration.
 */
final class LedgerSchemaProvider implements SchemaProvider
{
    public function createSchema(): Schema
    {
        $schema = new Schema();

        $this->events($schema);
        $this->idempotencyKeys($schema);
        $this->accountBalances($schema);
        $this->accountStatement($schema);
        $this->projectionCheckpoints($schema);

        return $schema;
    }

    private function events(Schema $schema): void
    {
        $table = $schema->createTable('events');
        $table->addColumn('global_position', Types::BIGINT, ['autoincrement' => true]);
        $table->addColumn('event_id', Types::GUID);
        $table->addColumn('stream_type', Types::STRING, ['length' => 128]);
        $table->addColumn('stream_id', Types::STRING, ['length' => 128]);
        $table->addColumn('version', Types::INTEGER);
        $table->addColumn('event_type', Types::STRING, ['length' => 255]);
        $table->addColumn('schema_version', Types::INTEGER);
        $table->addColumn('payload', Types::JSON, ['platformOptions' => ['jsonb' => true]]);
        $table->addColumn('metadata', Types::JSON, ['platformOptions' => ['jsonb' => true]]);
        $table->addColumn('occurred_at', Types::DATETIMETZ_IMMUTABLE);
        $table->addColumn('recorded_at', Types::DATETIMETZ_IMMUTABLE);
        $table->setPrimaryKey(['global_position']);
        $table->addUniqueIndex(['stream_type', 'stream_id', 'version'], 'uniq_events_stream_version');
        $table->addUniqueIndex(['event_id'], 'uniq_events_event_id');
    }

    private function idempotencyKeys(Schema $schema): void
    {
        $table = $schema->createTable('idempotency_keys');
        $table->addColumn('idempotency_key', Types::STRING, ['length' => 255]);
        $table->addColumn('route', Types::STRING, ['length' => 255]);
        $table->addColumn('request_hash', Types::STRING, ['length' => 128]);
        $table->addColumn('status', Types::STRING, ['length' => 16]);
        $table->addColumn('response_status', Types::INTEGER, ['notnull' => false]);
        $table->addColumn('response_headers', Types::JSON, ['notnull' => false, 'platformOptions' => ['jsonb' => true]]);
        $table->addColumn('response_body', Types::TEXT, ['notnull' => false]);
        $table->addColumn('created_at', Types::DATETIMETZ_IMMUTABLE);
        $table->addColumn('completed_at', Types::DATETIMETZ_IMMUTABLE, ['notnull' => false]);
        $table->addColumn('expires_at', Types::DATETIMETZ_IMMUTABLE, ['notnull' => false]);
        $table->setPrimaryKey(['idempotency_key', 'route']);
        $table->addIndex(['expires_at'], 'idx_idempotency_expires_at');
    }

    private function accountBalances(Schema $schema): void
    {
        $table = $schema->createTable('account_balances');
        $table->addColumn('account_id', Types::STRING, ['length' => 128]);
        $table->addColumn('currency', Types::STRING, ['length' => 3]);
        $table->addColumn('available', Types::BIGINT);
        $table->addColumn('reserved', Types::BIGINT);
        $table->addColumn('total', Types::BIGINT);
        $table->addColumn('version', Types::INTEGER);
        $table->addColumn('updated_at', Types::DATETIMETZ_IMMUTABLE);
        $table->setPrimaryKey(['account_id']);
    }

    private function accountStatement(Schema $schema): void
    {
        $table = $schema->createTable('account_statement');
        $table->addColumn('id', Types::BIGINT, ['autoincrement' => true]);
        $table->addColumn('account_id', Types::STRING, ['length' => 128]);
        $table->addColumn('global_position', Types::BIGINT);
        $table->addColumn('entry_type', Types::STRING, ['length' => 32]);
        $table->addColumn('amount', Types::BIGINT);
        $table->addColumn('currency', Types::STRING, ['length' => 3]);
        $table->addColumn('occurred_at', Types::DATETIMETZ_IMMUTABLE);
        $table->setPrimaryKey(['id']);
        $table->addUniqueIndex(['global_position'], 'uniq_statement_global_position');
        $table->addIndex(['account_id', 'global_position'], 'idx_statement_account');
    }

    private function projectionCheckpoints(Schema $schema): void
    {
        $table = $schema->createTable('projection_checkpoints');
        $table->addColumn('name', Types::STRING, ['length' => 64]);
        $table->addColumn('position', Types::BIGINT);
        $table->addColumn('updated_at', Types::DATETIMETZ_IMMUTABLE);
        $table->setPrimaryKey(['name']);
    }
}
